---
name: default
on: [push]

jobs:
  scripts-for-maven:
    name: Test scripts for Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install bats(bash testing framework)
        run: sudo bats/install-bats.sh
      - name: Run tests
        run: $GITHUB_WORKSPACE/bats/run-bats.sh ./
        working-directory: maven/test
  scripts-for-aws:
    name: Test scripts for AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install bats(bash testing framework)
        run: sudo bats/install-bats.sh
      - name: Run tests
        run: $GITHUB_WORKSPACE/bats/run-bats.sh ./
        working-directory: aws/test
  scripts-for-docker:
    name: Test scripts for Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install bats(bash testing framework)
        run: sudo bats/install-bats.sh
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.package_token }}
        run: $GITHUB_WORKSPACE/bats/run-bats.sh ./
        working-directory: docker/test
  dockerfile-cassandra-migrate:
    name: Test Dockerfile(cassandra-migrate)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build image
        run: docker build -t cassandra-migrate:ci-local .
        working-directory: docker/cassandra-migrate
      - name: Run image
        run: docker run --rm cassandra-migrate:ci-local
