---
name: default
on: [push]

jobs:
  test-scripts-for-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install bats(bash testing framework)
        run: bats/install-bats.sh
      - name: Run tests
        run: $GITHUB_WORKSPACE/bats/run-bats.sh .
        working-directory: maven/test
  test-scripts-for-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install bats(bash testing framework)
        run: bats/install-bats.sh
      - name: Run tests
        run: $GITHUB_WORKSPACE/bats/run-bats.sh .
        working-directory: aws/test
